Issue MNT Add behat tests
silverstripe/silverstripe-totp-authenticator pull request #80
Opened 2021-09-29 07:30 UTC by emteknetnz

Issue https://github.com/silverstripeltd/product-issues/issues/473

2021-11-15 02:08 UTC, maxime-rainville requested changes
Build is still failing on travis: https://app.travis-ci.com/github/silverstripe/silverstripe-totp-authenticator/builds/241725768

2021-11-15 04:22 UTC, emteknetnz commented
This is failing in travis though behat passed in github actions :-/

Fail
https://app.travis-ci.com/github/silverstripe/silverstripe-totp-authenticator/jobs/548053589#L1615

Pass
https://github.com/silverstripe/silverstripe-totp-authenticator/runs/4206674802?check_suite_focus=true#step:12:139

2021-11-15 10:01 UTC, maxime-rainville commented
I ran the behat test locally and was getting the same error we're seeing on Travis until I added a `SS_MFA_SECRET_KEY` value to my environment. I couldn't find any reference to `SS_MFA_SECRET_KEY` in the raw travis log, so that's probably what's wrong.

2021-11-15 10:02 UTC, maxime-rainville commented on .travis.yml
> +    - REQUIRE_FRAMEWORKTEST="^0.4.2"
```suggestion
    - REQUIRE_FRAMEWORKTEST="^0.4.2"
    - SS_MFA_SECRET_KEY=TEST123
```

2021-11-18 04:13 UTC, maxime-rainville approved these changes
LGTM

2021-11-18 04:13 UTC, merged